"""add user table

Revision ID: 3754417fd5b7
Revises: b29a1eca7265
Create Date: 2025-03-21 16:12:30.162729

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3754417fd5b7"
down_revision: Union[str, None] = "b29a1eca7265"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UserProfile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("passoword", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("tasks", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "tasks", "UserProfile", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'tasks', type_='foreignkey')
    # op.drop_column('tasks', 'user_id')
    # op.drop_table('UserProfile')
    # ### end Alembic commands ###
