"""add task fk on user

Revision ID: 34571491f5d6
Revises: 8a81d9e72c7b
Create Date: 2025-03-21 16:07:38.615625

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34571491f5d6"
down_revision: Union[str, None] = "8a81d9e72c7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UserProfile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("passoword", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("tasks", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "tasks", "UserProfile", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_column("tasks", "user_id")
    op.drop_table("UserProfile")
    # ### end Alembic commands ###
