"""Initial migration

Revision ID: 9e8ba0e6ef4e
Revises:
Create Date: 2025-03-10 18:06:14.233317

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e8ba0e6ef4e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("p_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks_categories",
        sa.Column("tasks_id", sa.Integer(), nullable=False),
        sa.Column("categories_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["categories_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tasks_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("tasks_id", "categories_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks_categories")
    op.drop_table("tasks")
    op.drop_table("categories")
    # ### end Alembic commands ###
